name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: app.py

    - name: Run tests
      run: |
        pytest # Replace with your test command (e.g., 'python -m unittest', 'nose2', etc.)
      working-directory: app.py
    - name: Start Flask Application
      run: |
        pip install gunicorn  
        gunicorn -w 4 -b 0.0.0.0:8000 your_app:app  
      working-directory: 
